name: "Pause Action"
description: "Orchestrates resume generation using Bun and TypeScript"
author: "sushruth"
inputs:
  resume_file:
    description: "Path to the resume.json file (e.g., .github/resume.json)"
    required: true
  templates:
    description: "Newline-separated list of template repository URLs (e.g., github.com/username/pause-template-latex)"
    required: true
  github_token:
    description: "GitHub token for API access (used to clone templates)"
    required: true
  create_release:
    description: "Whether to create a GitHub release with generated artifacts"
    required: false
    default: "false"
  release_tag:
    description: "Release tag (e.g., v1.0.0). If not provided, auto-generates based on timestamp"
    required: false
  changelog_source:
    description: "Source for changelog generation: 'commits' (default), 'file', or 'manual'"
    required: false
    default: "commits"
  changelog_file:
    description: "Path to changelog file when changelog_source is 'file'"
    required: false
  changelog_text:
    description: "Manual changelog text when changelog_source is 'manual'"
    required: false
  deploy_github_pages:
    description: "Template to deploy to GitHub Pages (e.g., 'html-template'). Set to 'false' or leave empty to disable."
    required: false
    default: "false"
  artifact_name_template:
    description: "Template string for artifact names (e.g., '{name} {MMM} {yyyy} Resume'). Use {name} for resume name, {yyyy} for year, {MMM} for month"
    required: false
runs:
  using: "composite"
  steps:
    - name: Cache build tools (gomplate, tectonic, typst)
      uses: actions/cache@v4
      with:
        path: /opt/hostedtoolcache/gomplate/4.3.0
        key: pause-gomplate-4.3.0
      id: cache-gomplate

    - name: Cache build tools (tectonic)
      uses: actions/cache@v4
      with:
        path: /opt/hostedtoolcache/tectonic/0.15.0
        key: pause-tectonic-0.15.0
      id: cache-tectonic

    - name: Cache build tools (typst)
      uses: actions/cache@v4
      with:
        path: /opt/hostedtoolcache/typst/0.11.0
        key: pause-typst-0.11.0
      id: cache-typst

    - name: Cache Tectonic TeX Live packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/Tectonic
        key: pause-tectonic-texlive

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: pause-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: pause-bun-

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        bun install

    - name: Run Pause Action
      shell: bash
      run: |
        cd ${{ github.action_path }}
        bun run src/index.ts
      env:
        INPUT_RESUME_FILE: ${{ inputs.resume_file }}
        INPUT_TEMPLATES: ${{ inputs.templates }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_CREATE_RELEASE: ${{ inputs.create_release }}
        INPUT_RELEASE_TAG: ${{ inputs.release_tag }}
        INPUT_CHANGELOG_SOURCE: ${{ inputs.changelog_source }}
        INPUT_CHANGELOG_FILE: ${{ inputs.changelog_file }}
        INPUT_CHANGELOG_TEXT: ${{ inputs.changelog_text }}
        INPUT_DEPLOY_GITHUB_PAGES: ${{ inputs.deploy_github_pages }}
        INPUT_ARTIFACT_NAME_TEMPLATE: ${{ inputs.artifact_name_template }}
